### ISSUE TITLE
Mobile Layout Issues

### ISSUE THREAD

**Issue by techcloudent** [asikart/quickicons#10]
This isn't really an issue but a simply modification to the akquickicons.css file in the following folder: administrator/modules/mod_akquickicons/css

Basically the issue is that when on a smartphone the layout only shows one icon instead of two and is a bit of a waste of space. 
![wp_ss_20140906_0001](https://cloud.githubusercontent.com/assets/8676072/4174609/e8586c4c-359a-11e4-9d6d-f2ab8e88021a.png)

#### A simple mod to line 3 in line of akquickicons.css will fix it:
```
padding: 5px 0 5px 10px;
```
to this
```
padding: 5px 0 5px 5px;
```

So simply change that 10px padding to 5px padding and the layout renders in two columns.
![wp_ss_20140906_0004](https://cloud.githubusercontent.com/assets/8676072/4174611/0e1e5ebe-359b-11e4-8f08-a63555b7ab0d.png)

The layout still renders in 3 columns after the modification when the phone is held horizontally:
![wp_ss_20140906_0006](https://cloud.githubusercontent.com/assets/8676072/4174616/4141eda6-359b-11e4-91e6-3ff21145b5b0.png)

The screenshots were taken on a Windows Phone (8.1) with the Internet Explorer App. The issue occurs as pictured on iOS and Android smartphones too. 

I've been making this small mod in my installation for a while and thought I might suggest it for the release version so others could benefit. I don't mind if it isn't implemented.

**Comment by asika32764** [comment]
I missed this issue for 2.0.2. I'll implement it maybe in 2.0.3.
