### ISSUE TITLE
No more category tabs since Update to Joomla 3.3

### ISSUE THREAD

**Issue by PascalNetenvie** [asikart/quickicons#11]
Hi,
As said in title since Joomla 3.3 update there is no more category tabs display ...
If i look in HTML code ul with class "nav nav-tabs" is empty.

Problem both the same with v1.1.8 Pro  and v 2.0.1

As this is generated by Bootstrap function, perhaps bootstrap have been updated and your code not ...

Regards.

**Comment by asika32764** [comment]
This problem maybe is a script conflict between AQI and other plugins. Please try to install AQI in a new pure Joomla to check that is this problem occurred again or not.

**Comment by PascalNetenvie** [comment]
This problem solved by itself after another update.
