### ISSUE TITLE
unable to publish Icons

### ISSUE THREAD

**Issue by anirudh7** [asikart/quickicons#13]
I am getting error "Published but is pending" and I cant able to see the icon. I tried unpublished and publish but still the same and cant delete the icons but that's whole different issue though, I can still unpublish so I can live with it
![freestyle event photogaphy administration icons](https://cloud.githubusercontent.com/assets/5333996/4436909/5e4bc8a2-4786-11e4-8c72-111b5ca8ba3e.png)

**Comment by asika32764** [comment]
[2.0.2](https://github.com/asikart/quickicons/releases/tag/2.0.2) has released, this issue should be fixed. Please try it.
