### ISSUE TITLE
500 Library path /libraries/framework cannot be found. 

### ISSUE THREAD

**Issue by micker** [asikart/quickicons#17]
when i try to install last version (jed install, upload tar, tmp install)
i have this error  on component

An error has occurred.

    500 Library path /libraries/framework cannot be found.

**Comment by micker** [comment]
noboy ?

**Comment by asika32764** [comment]
Hi, Could you check that is this folder exists?

If exists, what is the permission number of this folder?

**Comment by asika32764** [comment]
Do you install it on Joomla 3.4?

Joomla 3.4 removed this folder, please add it before we fix this bug.

See: https://github.com/joomla/joomla-cms/tree/staging/libraries

**Comment by micker** [comment]
yes i am on j3.4 testing all folder winwalker are here and chmod were good
can you explain more about
"Joomla 3.4 removed this folder, please add it before we fix this bug."
thanks

**Comment by asika32764** [comment]
Joomla 3.4 removed libraries/framework folder. Try create this folder to
get rid of this error.


Berges Yannick <notifications@github.com> 於 2015年2月13日 星期五寫道：

> yes i am on j3.4 testing all folder winwalker are here and chmod were good
> can you explain more about
> "Joomla 3.4 removed this folder, please add it before we fix this bug."
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asikart/quickicons/issues/17#issuecomment-74216005>.
>


-- 
Best Regard

Simon Asika | Kwang Po Tung | 董冠伯
------------------------------------------------
- Founder: Asikart Extension <http://ext.asikart.com/>
- CTO: SMS Taiwan <http://www.bm-sms.com.tw/>

- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by micker** [comment]
great ! work just need to create an empty framework folder
thanks

**Comment by asika32764** [comment]
Should be fixed in [2.0.3](https://github.com/asikart/quickicons/releases/tag/2.0.3)
