### ISSUE TITLE
Solution of [500 Library path /libraries/framework cannot be found.] in Joomla 3.4

### ISSUE THREAD

**Issue by asika32764** [asikart/quickicons#19]
Joomla 3.4 has removed `/libraries/framework` folder so caused this error.

Just create an empty folder at Joomla `/libraries/framework`, then everything will working well.

Please wait our next release to fix this issue.

**Comment by micker** [comment]
not solved in 3.4 final

**Comment by asika32764** [comment]
It works for me after created this folder

![p-2015-02-26-1](https://cloud.githubusercontent.com/assets/1639206/6392117/57bf6500-bdf8-11e4-83ce-20dad086faac.jpg)

**Comment by micker** [comment]
yes i know maybe add create folder in script installation ?

**Comment by kanelaoka2** [comment]
here also did not work .. any other options?

thank you

**Comment by fabricioventura** [comment]
Also with the same problem.
I tried all the steps and still giving problems installing.

I'm trying to install the latest version here from github.

"error
No files selected

Could not find the package installation "

**Comment by asika32764** [comment]
Should be fixed in [2.0.3](https://github.com/asikart/quickicons/releases/tag/2.0.3)

**Comment by fabricioventura** [comment]
error
No files selected

Could not find the installation package

**Comment by waynejb** [comment]
Issues installing with Joomla 3.4.1
Error
Unable to write entry
Unable to find install package

**Comment by asika32764** [comment]
See here: https://github.com/asikart/quickicons/issues/20#issuecomment-78516667
