### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rbush89** [asikart/quickicons#20]
I updated my Joomla from 3.3.6 to 3.4 and the quickicons component stopped working. I uninstalled and tried to re-install but I am getting this error: "Error No file selected. Unable to find install package"

**Comment by asika32764** [comment]
The steps to solve this issue:

- Remove admin `components/com_akquickicons` folder.
- Open phpMyAdmin, go to `#__extensions` table, find `com_akquickicons`, delete it if exists.
- Go to `#__menus` table, delete `com_akquickicons` menu if exists.
- See this page to fix error in 3.4: https://github.com/asikart/quickicons/issues/19
- Re-install it

**Comment by rbush89** [comment]
That did not work.
The only folder that existed was the images/quickicons.
Still getting the same error when I try to install.

That's okay though, all I needed it for was to create an icon that was basically a bookmark to a link. So I just bookmarked the link in my browser and that works fine.

**Comment by petervanakkeren** [comment]
Hi, same trouble here.

The zip installer gives:
Error
No file selected.
Unable to find install package

The tar.gz package times out and then gives a blank page.

**Comment by asika32764** [comment]
It seems Joomla dis not found the XML manifest file in `admin/quickicons.xml`, Could you try unarchive component to temp folder and install it?

**Comment by fabricioventura** [comment]
Also with the same problem.
I tried all the steps and still giving problems installing.

I'm trying to install the latest version here from github.

"error
No files selected

Could not find the package installation "

also tried installing the 1.1.8 version is successfully executed, but unable to access the component, appears to get a blank page.

This expensão is wonderful, I await your precious help!

**Comment by carosouza** [comment]
Hello, I tried to install the version 2.0.2 in joomla 3.4, but does not install and nothing happens, thank you.

**Comment by asika32764** [comment]
It seems too many issues in Joomla 3.4 (But I have worked well on my computer)

I need more time to find the reason, these issues caused by some BC break of Joomla 3.4. So there may be much parts I have to change of my extensions.

Since it is many extensions breaks and I have heavy work of my job recently, I'll release new versions after April, please everybody wait for it.

Thank you.

**Comment by fabricioventura** [comment]
Thanks for the reply!

I'll wait then. I'm in the waiting!

Thank you very much!

**Comment by petervanakkeren** [comment]
What worked for me in the meantime in Joomla 3.4:
create a folder /libraries/framework manually
re-install version 2.0.1

**Comment by fabricioventura** [comment]
petervanakkeren 

Here failed.

I created the folder manually
I uninstalled all versions
Reinstalled the version 2.0.1

The component is active, but can not access it.
![not-found](https://cloud.githubusercontent.com/assets/11294378/6467912/25077aa6-c1b0-11e4-8086-8f7df5cf27f2.png)

**Comment by fabricioventura** [comment]
I think I managed to solve!

-I Created the folder manually
-I Uninstalled all versions
-Reinstalled The version 2.0.1

Then I got the latest version here from github:

Url: https://github.com/asikart/quickicons

  and transfer the folders manually, they are:

/ administrator / components / com_akquickicons
/ administrator / modules / mod_akquickicons
/ libraries / windwalker

Solved my problem :)

**Comment by fabricioventura** [comment]
FAIL!

Getting access. But with many problems. for almost everything, generates the error 404!

**Comment by asika32764** [comment]
I can't reproduce this issue, could you open debug mode and get the screenshot?

![p-2015-03-11-6](https://cloud.githubusercontent.com/assets/1639206/6590913/4e97591a-c7f3-11e4-9c8c-7805ca0c633e.jpg)

![p-2015-03-11-5](https://cloud.githubusercontent.com/assets/1639206/6590914/4e9ed672-c7f3-11e4-9abf-fd293dd7c731.jpg)

**Comment by fabricioventura** [comment]
New version error 2.0.3:

error
No files selected

Could not find the installation package

**Comment by asika32764** [comment]
Please tell me your server information:

- OS
- Upload limit
- php safe mode?
- php version

Or please try install AQI in other server so we can check if it caused by environment.

**Comment by fabricioventura** [comment]
Hello Asika !!!

-Windows 8.1 / Firefox and Chrome
-PHP Settings: https://www.dropbox.com/s/urq7cut21bz07lt/cPanel%20X.png?dl=0
-Joomla 3.4

Thanks for support!

**Comment by asika32764** [comment]
Maybe caused by a Joomla 3.4 bug, see: https://docs.joomla.org/J3.x:Extension_won't_install/en

**Comment by asika32764** [comment]
> Extra security checks for PHP files were added for file uploads in JFile::upload. Unfortunately these were not disabled for the extension installer meaning any uncompressed zip files were interpreted as insecure and therefore not installed.

Try this re-compressed package, I think this one is able to install
https://github.com/asikart/quickicons/releases/download/2.0.3/com_quickicons-2.0.3-hotfix-for-j3.4.zip

**Comment by fabricioventura** [comment]
WOW! That'S Perfect!

It worked perfectly in Joomla 3.4!

Thank you for the support and for your dedication!

**Comment by fabricioventura** [comment]
WOW! That'S Perfect!

It worked perfectly in Joomla 3.4!

Thank you for the support and for your dedication!

**Comment by waynejb** [comment]
Tried a number of suggestions to get this to install on Joomla 3.4.1 with no luck.  Unable to write Entry/Unable to Find Install package.
![installerrorqi](https://cloud.githubusercontent.com/assets/8862377/7573963/c0230820-f7f7-11e4-9250-6937a245cb30.jpg)

**Comment by asika32764** [comment]
Try un-compress AQI package and re-compress it, or upload AQI to tmp folder to install it.

This is a re-compressed package: https://github.com/asikart/quickicons/releases/download/2.0.3/com_quickicons-2.0.3-hotfix-for-j3.4.zip

**Comment by waynejb** [comment]
Was able to get that to load.  When you go to Components then QuickIcons I get Server 500 error.  The module is working.  It also is asking for version 2.04 but fails with Unable to Write Entry.

**Comment by waynejb** [comment]
We uncompressed and re-compressed and this did not solve the issue. What next?

**Comment by waynejb** [comment]
After long investigation we noticed that it won't install in Joomla 3.4.1.  We needed to install version 3.2 of QuickIcons then manually extract the files from 3.4 version into the correct directories.
