### ISSUE TITLE
asstets table database entries for icons: something is going wrong

### ISSUE THREAD

**Issue by mc-cm** [asikart/quickicons#25]
Hello!
This might be just a small detail, but nevertheless I'd like to share it.
When an icon is created the component makes two entries in the database:
- in #_akquickicons_icons for the icon itself
- in #_assets for the acl settings

The entry in the **assets table** seems to be wrong:
1) the `parent_id` field does not get filled with the correct ID of the category which the icon is saved to.
2) the `level` field gets not populated with the correct value. It should be `level of the category`+1. Instead of this the value is **always** `1`;
3) the `name` and the `title` field get strange values: `#__akquickicons_icons.2` (2 is the id of the associated icon). The value should be `com_akquickicons.icons.2`.

Maybe I'm wrong, but please look at that and give me some feedback. I tested many Joomla! addons and found very similar procedures and schemas regarding the database side.
Unfortunately I don't have the knowledge and ability to fix something like that by myself for I don't know enough php. Otherwise I would be happy to contribute.
So I just guess that something is not quite right here. I have a special situation here and need to make sure that I use addons that not just work at the outside (backend / frontend) but also on the inside (database).

Thanks a lot for your efforts.
Chris

**Comment by DavidBoggitt** [comment]
I noticed something that might be related when installing version 2.0.3 on a clean install of J3.4.1.

I always check permissions/assets with ACL Manager and the image below shows what it detected:

![asikart-quickicons](https://cloud.githubusercontent.com/assets/3079738/6768983/de10a3f6-d07e-11e4-85c8-3509f6824785.png)

**Comment by asika32764** [comment]
Try to open an icon item and re-save it, Joomla should fix the asset of this item.

If it doesn't, I think maybe it is a new bug in current Joomla version, but I need more time to check the reason.

**Comment by DavidBoggitt** [comment]
I have seen this before on earlier versions of Joomla, but I will try what you suggest.  Thanks :)

**Comment by asika32764** [comment]
Some code has written before Joomla 3.1, so I have to test it in newest Joomla.

**Comment by DavidBoggitt** [comment]
Ok - thank-you!

**Comment by mc-cm** [comment]
> Try to open an icon item and re-save it, Joomla should fix the asset of this item.

Hello Askia!
Please do the tests on J! 3.4.x.
Opening and saving the Icons does not alter or correct anything in the assets table.

Thanks a lot!
![akquickicons](https://cloud.githubusercontent.com/assets/1061216/6780017/c9b888f4-d161-11e4-8663-6b1ee8172138.png)

**Comment by mc-cm** [comment]
any news on this?
Thanks a lot for your efforts!

Chris

**Comment by mc-cm** [comment]
@asika32764 : Sorry, don't want to be rude. But to have some feedback on my last question would be very nice.
Or - maybe - someone else can fix this, helping to improve this great extension?

Thanks
Chris

**Comment by asika32764** [comment]
Sorry, I'm still in some big projects of my job, so I can only keep extensions just work now.

Is this issue caused any bug or error? If there are serious error, please tell me, I'll try to make the priority of this issue higher.

Thank you.

**Comment by asika32764** [comment]
This should fixed in 2.0.8
