### ISSUE TITLE
404 on file

### ISSUE THREAD

**Issue by CKENT0369** [asikart/quickicons#27]
When watching console on the the load of the admin control panel I get this. 

NetworkError: 404 Not Found - http://mysites.com/administrator/components/com_akquickicons/includes/akicons/css/akicons.css"

I checked the for the folder and the includes folder is not in the directory at all. Maybe a file reference needs changed.

**Comment by asika32764** [comment]
Fixed in [2.0.4](https://github.com/asikart/quickicons/releases/tag/2.0.4)
