### ISSUE TITLE
Any warning to update Asikart from Joomla 2.5 to the last 3?

### ISSUE THREAD

**Issue by Chacapamac** [asikart/quickicons#29]
I have a site with Joomla 2.5.28 with Asikart Quick Icons 1.1.8 component & Asikart QuickIcons Module 1.4. 

I need to update to the last Joomla 3 version available.

My main question:
Any warning or way to do to be sure it go smootly ?

Also (less important):
Are the problems with Akeeba Geoip system plugin are fix ?

**Comment by asika32764** [comment]
First question, you can remove AQI and re-install it after upgrade to 3.4, the data should be remain.

And about the GEO plugin, it is already fixed by Akeeba, you must install the newest one.

**Comment by Chacapamac** [comment]
A 1000 time thank you — Great stuff & GOOD DAY!

**Comment by Chacapamac** [comment]
Sorry to come back - Do I have to uninstall both Component and Module ?

**Comment by asika32764** [comment]
Sorry for lone time to reply, just uninstall component or both.
