### ISSUE TITLE
icons in administrator/components/com_akquickicons/images/quickicons

### ISSUE THREAD

**Issue by mc-cm** [asikart/quickicons#31]
Hi there!
Is there a reason why pictures are delivered twice? one time in ```images/quickicons```, one more time in ```administrator/components/com_akquickicons/images/quickicons```.
As mentioned in #24 I don't need the additional images. Looking through the extension a second time I was stunned to find them also in the admin/component folder.
I deleted them for testing purposes, no error so far. But I don't know what is going on "under the hood". So please, can you confirm quickly that I can delete the icons here too if not needed.

Thanks a lot.
Chris

**Comment by asika32764** [comment]
Yes, you can delete the images folder which in `components/com_akquickicons`

It is just a backup, AQI will copy this folder to `/images` when first installing.

**Comment by mc-cm** [comment]
thanks
