### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by adambako** [asikart/quickicons#32]
hi.
i have latest joomla 3.4.3.
also i have your latest quickicons version..
i dont know what happend but when i want to open akistart component i get this error

```
Fatal error: Namespace declaration statement has to be the very first statement in the script in /.../www/libraries/windwalker/src/Windwalker.php on line 9
```

i cant find anything on the web.. i see its some joomla library.. did you know something about this issue?
thx

**Comment by asika32764** [comment]
AQI is working fine on my site.

I think it's maybe something included before namespace of this file.

Could you check is there any other code, whitespace or [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) appeared before the namespace?
