### ISSUE TITLE
tabs mode ?? title in 

### ISSUE THREAD

**Issue by micker** [asikart/quickicons#34]
hello it strange the tabs mode doesn't exist ?

**Comment by asika32764** [comment]
It still exists, could you check that is there any js conflict in Dev tools?

**Comment by micker** [comment]
sorry i understand now ... => need to display multi cat in same module ...
question ordering doesn't work well .... realy strange
![snip_20160330142904](https://cloud.githubusercontent.com/assets/2539440/14142093/d77aee30-f683-11e5-9d7b-5a44074ae33a.png)
![snip_20160330142942](https://cloud.githubusercontent.com/assets/2539440/14142094/d77d169c-f683-11e5-9290-05229c85fd78.png)

**Comment by micker** [comment]
i can't find a good way to have good order ...

**Comment by asika32764** [comment]
OK, I can confirm that the ordering issue is a bug, please wait for next release.

Before new version release, you can modify `libraries/windwalker/src/Model/ListModel.php` file line `887`

Change

``` php
preg_replace('/\s+/', ' ', trim($value));
```

To 

``` php
$value = preg_replace('/\s+/', ' ', trim($value));
```

I think it will be fixed.

**Comment by asika32764** [comment]
Should be fixed now.
