### ISSUE TITLE
Error "Invalid jQuery UI configuration. "

### ISSUE THREAD

**Issue by diegofcv** [asikart/quickicons#35]
Hi, I installed version 2.0.6 and had an error **"Invalid jQuery UI configuration. Selectable, draggable and droppable components must be included."** when I try to access "Images Manager". In my log files I saw the warning bellow. Also, I installed 2.0.4 and I was able to access the "Images Manager" without problem.

[Tue Apr 26 09:40:27.564132 2016] [:error] [pid 6754] [client 191.176.249.128:48280] PHP Warning:  Invalid argument supplied for foreach() in /var/www/sindy/libraries/windwalker/src/View/Html/ListHtmlView.php on line 67, referer: http://sindy.dotpro.com.br/administrator/index.php?option=com_akquickicons

Saw another issue with the same message, where the user said it solved it checking security stuff. I checked mine, turned off security improvements, but no difference. As it works with 2.0.4, I think it's not my environment.

Thank you!

**Comment by asika32764** [comment]
Should be fixed in 2.0.8
