### ISSUE TITLE
QuickIcons vs Joomla 3.6.0 beta

### ISSUE THREAD

**Issue by ferino75** [asikart/quickicons#40]
Hello,
I try Joomla 3.6.0 beta2
Quickicons v2.0.7 or 2.0.8 
I get error:
" 0 Call to undefined method modAkquickiconsHelper::escape()"

**Comment by asika32764** [comment]
AQI works fine in Joomla 3.6.0 beta2 on my machine

![p-2016-06-22-006](https://cloud.githubusercontent.com/assets/1639206/16255022/59b038b6-3878-11e6-9afb-5778c6c744d6.jpg)


Could you provide your system information?

**Comment by ferino75** [comment]
PHP Built On 	Linux vm009 2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64
Database Version 	5.1.73
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8_general_ci
PHP Version 	7.0.2
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.6.0-beta2 Beta [ Noether ] 16-June-2016 13:54 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by ferino75** [comment]
I found the following:
On the 1. site I have
Asikart QuickIcons Module version 2.0.5  - there is a problem
On the 2. site I have older version
Asikart QuickIcons Module version 1.4  - there is no problem.

**Comment by ferino75** [comment]
I reinstalled Quickicons to version 1.1.8 on 1. site.
Asikart QuickIcons Module is working OK, 
but there is warning in Component - Asikart QuickIcons - edit icon:

"Warning: Declaration of AKModelAdmin::prepareTable(&$table) should be compatible with JModelAdmin::prepareTable($table) in /home/sq016100/www_root/administrator/components/com_akquickicons/windwalker/component/modeladmin.php on line 22"

**Comment by DavidBoggitt** [comment]
Same problem here, after updating a site from 3.5.1 to 3.6.0

Call to undefined method modAkquickiconsHelper::escape()

Tried reinstalling 2.0.7, but same problem.  Unpublished module for the moment.

System information below:

PHP Built On	Linux uk601.directrouter.com 2.6.32-531.29.2.lve1.3.11.1.el6.x86_64 #1 SMP Thu Dec 18 06:49:17 EST 2014 x86_64
Database Version	5.6.30
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.8
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.6.0 Stable [ Noether ] 12-July-2016 21:14 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by asika32764** [comment]
I can confirm this issue in a old version on Linux.

There are an old module file located on `administrator/modules/mod_akquickicons/helper.php`

This file may not be deleted when AQI auto-updated, so you can manually delete this file, I think everything will back to normal.

**Comment by ferino75** [comment]
Thank you, it helped.

**Comment by techcloudent** [comment]
Thanks @asika32764 for sharing this solution. Fixed my issue immediately. :-)
