### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by micker** [asikart/quickicons#42]
hello on last version of asikart and joomla 3.6.2 we have a blank page if module is use in cpanel ....
i am trying error reporting to maximum ... but no error

**Comment by asika32764** [comment]
Could you check out this issue https://github.com/lyrasoft/quickicons/issues/40 to check is it same problem?

**Comment by micker** [comment]
no i am trying to update by ftp but error is same ... blanck page with some code in source

<div class="row-fluid">
			<div class="span3">
			<div class="cpanel-links">

**Comment by asika32764** [comment]
What OS do you use and have you ever try install AQI in a pure new Joomla?

I need to know there is a module conflict or not.

**Comment by micker** [comment]
.. it works i need too check module in administration
