### ISSUE TITLE
0 Class 'Windwalker\Cache\Cache' not found

### ISSUE THREAD

**Issue by dvddvddvd** [asikart/quickicons#44]
![patallazo](https://cloud.githubusercontent.com/assets/23082493/19736353/2f460b2e-9baf-11e6-9c86-c06bc9014173.jpg)

Hello,
I currently use Joomla! 3.6.4, an update in me got the message shown in the image: "Class 0 'Windwalker \ Cache \ Cache' not found"

I have installed:

Asikart QuickIcons
Component Manager 2.0.6

Asikart QuickIcons Module
Module Manager 2.0.5

I have not been able to solve the problem.

Thank you

**Comment by asika32764** [comment]
Should fixed now.
