### ISSUE TITLE
Checking Joomla, Checking Extensions icons

### ISSUE THREAD

**Issue by beadar** [asikart/quickicons#47]
Hi,  I love your quickicons extension.  Have one question.  I can't seem to hide the Checking Joomla and Checking Extensions icons.  I can hide all the other ones but not those two.  Is there a way to do this.  I would like to give very limited access to some users on the admin backpage.
Thanks.

**Comment by asika32764** [comment]
Check the admin module and select `Use quickicon plugins` to `NO`.

![171220-0001](https://user-images.githubusercontent.com/1639206/34191803-d5d0984a-e584-11e7-81d2-7c964f3341bf.jpg)
