### ISSUE TITLE
unable to trash Icons

### ISSUE THREAD

**Issue by anirudh7** [asikart/quickicons#9]
I was trying to "trash" unwanted icons, as soon as hit trash, I get a Message
"1 item successfully trashed" but i can still see it as published and "Unpublish" was successful but again if "trash" unpublished icon its back to "Publish" but not trashed

**Comment by asika32764** [comment]
[2.0.2](https://github.com/asikart/quickicons/releases/tag/2.0.2) has released, this issue should be fixed. Please try it.
